[package]
name = "xlayer-reth-node"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "XLayer Reth Binary"

[lints]
workspace = true

[dependencies]
# internal
xlayer-builder.workspace = true
xlayer-flashblocks.workspace = true
xlayer-chainspec.workspace = true
xlayer-legacy-rpc.workspace = true
xlayer-monitor.workspace = true
xlayer-rpc.workspace = true
xlayer-version.workspace = true
xlayer-trace-monitor.workspace = true

# reth
reth.workspace = true
reth-optimism-node.workspace = true
reth-optimism-cli.workspace = true
reth-node-api.workspace = true
reth-node-builder.workspace = true
reth-optimism-evm.workspace = true
reth-optimism-payload-builder.workspace = true
reth-payload-builder.workspace = true
reth-cli-util.workspace = true
reth-rpc-server-types.workspace = true

# alloy
alloy-primitives.workspace = true
op-alloy-network.workspace = true

# misc
clap.workspace = true
tracing.workspace = true
url.workspace = true
eyre.workspace = true
humantime.workspace = true
either.workspace = true

[features]
default = []
jemalloc = ["reth-cli-util/jemalloc", "reth-optimism-cli/jemalloc"]
jemalloc-prof = ["reth-cli-util/jemalloc-prof"]
asm-keccak = ["alloy-primitives/asm-keccak"]
