[package]
name = "xlayer-legacy-migrate"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]

# Use workspace reth dependencies to ensure consistent versions
reth-db.workspace = true
reth-db-api.workspace = true
reth-cli.workspace = true
reth-cli-commands = { workspace = true, features = ["edge"] } 
reth-node-builder.workspace = true
reth-optimism-chainspec.workspace = true
reth-optimism-cli.workspace = true
reth-optimism-node.workspace = true
reth-primitives-traits.workspace = true
reth-provider = { workspace = true, features = ["rocksdb"] }
reth-static-file-types.workspace = true
reth-storage-api.workspace = true
reth-tracing.workspace = true

alloy-primitives.workspace = true

clap = { workspace = true, features = ["derive"] }
eyre.workspace = true
tokio.workspace = true
tracing.workspace = true
rayon.workspace = true

# Chainspec deps

# reth
reth-chainspec.workspace = true
reth-optimism-forks.workspace = true
reth-ethereum-forks.workspace = true

# ethereum
alloy-genesis = { version = "1.6.1", default-features = false }
alloy-consensus =  { version = "1.6.1", default-features = false }
alloy-eips = { version = "1.6.1", default-features = false }
alloy-chains = { version = "0.2.5", default-features = false }

# op
op-alloy-rpc-types = { workspace = true }

# misc
serde = { workspace = true }
serde_json = { workspace = true }
once_cell = { workspace = true }

[lints]
workspace = true
