[package]
name = "xlayer-reth-tools"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "XLayer Reth Tools - Import and Export utilities"

[lints]
workspace = true

[[bin]]
name = "xlayer-reth-tools"
path = "main.rs"

[dependencies]
# internal
xlayer-chainspec.workspace = true
xlayer-reth-import.workspace = true
xlayer-reth-export.workspace = true

# reth
reth-optimism-node.workspace = true
reth-optimism-evm.workspace = true
reth-optimism-chainspec.workspace = true
reth-cli-util.workspace = true
reth-optimism-consensus.workspace = true
reth-tracing.workspace = true

# tokio
tokio.workspace = true

# misc
clap.workspace = true
tracing.workspace = true

[features]
default = []
jemalloc = ["xlayer-reth-import/jemalloc", "xlayer-reth-export/jemalloc", "reth-cli-util/jemalloc"]
asm-keccak = ["xlayer-reth-import/asm-keccak", "xlayer-reth-export/asm-keccak"]

